Repository AY2021S1-CS2103T-W17-3/tp, pull requests merged in 2020-10, with the labels that each got.

#39 Refactor parser
  build.gradle
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/McGymmyParser.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/logic/parser/exceptions/ParameterConflictException.java
  src/main/java/seedu/address/logic/parser/parameter/AbstractParameter.java
  src/main/java/seedu/address/logic/parser/parameter/OptionalParameter.java
  src/main/java/seedu/address/logic/parser/parameter/Parameter.java
  src/main/java/seedu/address/logic/parser/parameter/ParameterConverter.java
  src/main/java/seedu/address/logic/parser/parameter/ParameterSet.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/McGymmyParserCommandsTest.java
  src/test/java/seedu/address/logic/parser/McGymmyParserTest.java
  src/test/java/seedu/address/logic/parser/parameter/OptionalParameterTest.java
  src/test/java/seedu/address/logic/parser/parameter/ParameterSetTest.java
  src/test/java/seedu/address/logic/parser/parameter/ParameterTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#53 Create fridge class
  src/main/java/seedu/address/model/food/Carbohydrate.java
  src/main/java/seedu/address/model/food/Fat.java
  src/main/java/seedu/address/model/food/Food.java
  src/main/java/seedu/address/model/food/Fridge.java
  src/main/java/seedu/address/model/food/Macronutrient.java
  src/main/java/seedu/address/model/food/Protein.java
  src/test/java/seedu/address/model/food/FoodTest.java
  src/test/java/seedu/address/model/food/FridgeTest.java
  src/test/java/seedu/address/model/food/MacronutrientTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
Labels: type.Enhancement

#64 Update Acknowledgement to include Apache Commons CLI
  README.md
Labels: documentation

#65 Tag command Suite
  src/main/java/jimmy/mcgymmy/logic/commands/AddCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/EditCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/TagCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/UnTagCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java
  src/main/java/jimmy/mcgymmy/model/food/Food.java
  src/test/java/jimmy/mcgymmy/logic/commands/AddCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/EditCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/TagCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/UnTagCommandTest.java
Labels: type.Enhancement

#71 Store mcgymmy data in a separate data folder
  src/main/java/jimmy/mcgymmy/model/UserPrefs.java
Labels: documentation

#69 Add test for Macronutrient
  src/test/java/jimmy/mcgymmy/model/food/MacronutrientTest.java
Labels: type.Bug, type.Enhancement

#63 Add Macro command
  src/main/java/jimmy/mcgymmy/logic/LogicManager.java
  src/main/java/jimmy/mcgymmy/logic/commands/Command.java
  src/main/java/jimmy/mcgymmy/logic/commands/CommandExecutable.java
  src/main/java/jimmy/mcgymmy/logic/macro/Macro.java
  src/main/java/jimmy/mcgymmy/logic/macro/MacroList.java
  src/main/java/jimmy/mcgymmy/logic/macro/NewMacroCommand.java
  src/main/java/jimmy/mcgymmy/logic/macro/exceptions/DuplicateMacroException.java
  src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java
  src/main/java/jimmy/mcgymmy/logic/parser/Parser.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/test/java/jimmy/mcgymmy/logic/macro/MacroListTest.java
  src/test/java/jimmy/mcgymmy/logic/macro/MacroTest.java
  src/test/java/jimmy/mcgymmy/logic/macro/NewMacroCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/CommandParserTestUtil.java
  src/test/java/jimmy/mcgymmy/logic/parser/McGymmyParserTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserCommandsTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserTest.java
Labels: type.Enhancement

#72 Update Main class to correct Mainclass in build.gradle
  build.gradle
Labels: priority.High, type.Bug

#68 Allow duplicates in food list
  src/main/java/jimmy/mcgymmy/logic/commands/AddCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/DeleteCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/EditCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/TagCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/UnTagCommand.java
  src/main/java/jimmy/mcgymmy/model/McGymmy.java
  src/main/java/jimmy/mcgymmy/model/Model.java
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/main/java/jimmy/mcgymmy/model/food/FoodMethodHandler.java
  src/main/java/jimmy/mcgymmy/model/food/Fridge.java
  src/main/java/jimmy/mcgymmy/model/food/UniqueFoodList.java
  src/main/java/jimmy/mcgymmy/model/food/exceptions/DuplicateFoodException.java
  src/main/java/jimmy/mcgymmy/model/food/exceptions/FoodNotFoundException.java
  src/test/java/jimmy/mcgymmy/logic/commands/AddCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/DeleteCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/EditCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/TagCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/UnTagCommandTest.java
  src/test/java/jimmy/mcgymmy/model/McGymmyTest.java
  src/test/java/jimmy/mcgymmy/model/food/UniqueFoodListTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonMcGymmyStorageTest.java
  src/test/java/jimmy/mcgymmy/testutil/TypicalFoods.java
Labels: type.Enhancement

#70 Add test for AddCommand
  src/test/java/jimmy/mcgymmy/logic/commands/AddCommandTest.java
Labels: type.Bug

#57 1.2 additional updates and minor bug fixes
  src/main/java/jimmy/mcgymmy/model/food/Food.java
  src/test/java/jimmy/mcgymmy/model/food/FoodTest.java
Labels: type.Bug

#78 Update User guide
  docs/UserGuide.md
  docs/images/CommandImagesForUG/Add.png
  docs/images/CommandImagesForUG/Alias.png
  docs/images/CommandImagesForUG/Delete.png
  docs/images/CommandImagesForUG/Edit.png
  docs/images/CommandImagesForUG/Find.png
  docs/images/CommandImagesForUG/Help.png
  docs/images/CommandImagesForUG/List.png
  docs/images/CommandImagesForUG/Macro.png
  docs/images/CommandImagesForUG/Tag.png
  docs/images/CommandImagesForUG/Untag.png
  docs/images/CommandImagesForUG/Update.png
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: documentation

#76 Implement help command
  src/main/java/jimmy/mcgymmy/logic/commands/AddCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ClearCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/DeleteCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/EditCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ExitCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/FindCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/HelpCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ListCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/TagCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/UnTagCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandHelpUtil.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/test/java/jimmy/mcgymmy/logic/commands/HelpCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/McGymmyParserTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserCommandsTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserTest.java
Labels: type.Enhancement

#81 Add date property
  src/main/java/jimmy/mcgymmy/logic/commands/AddCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/EditCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/main/java/jimmy/mcgymmy/model/date/Date.java
  src/main/java/jimmy/mcgymmy/model/food/Food.java
  src/main/java/jimmy/mcgymmy/model/tag/Tag.java
  src/main/java/jimmy/mcgymmy/model/util/SampleDataUtil.java
  src/main/java/jimmy/mcgymmy/storage/JsonAdaptedFood.java
  src/main/java/jimmy/mcgymmy/ui/FoodCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FoodListCard.fxml
  src/test/data/JsonSerializableMcGymmyTest/duplicateFoodMcGymmy.json
  src/test/data/JsonSerializableMcGymmyTest/typicalFoodMcGymmy.json
  src/test/java/jimmy/mcgymmy/logic/commands/AddCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/EditCommandTest.java
  src/test/java/jimmy/mcgymmy/model/date/DateTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonAdaptedFoodTest.java
  src/test/java/jimmy/mcgymmy/testutil/FoodBuilder.java
  src/test/java/jimmy/mcgymmy/testutil/TypicalFoods.java
Labels: type.Enhancement

#82 Extend find command so that it also find food by tag
  src/main/java/jimmy/mcgymmy/logic/commands/FindCommand.java
  src/main/java/jimmy/mcgymmy/logic/predicate/FoodContainsKeywordsPredicate.java
  src/main/java/jimmy/mcgymmy/logic/predicate/NameContainsKeywordsPredicate.java
  src/main/java/jimmy/mcgymmy/logic/predicate/TagContainsKeywordsPredicate.java
  src/test/java/jimmy/mcgymmy/logic/commands/CommandTestUtil.java
  src/test/java/jimmy/mcgymmy/logic/commands/FindCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/FoodContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/TagContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
Labels: type.Enhancement

#90 Remove duplicate check when creating tag
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
Labels: severity.Low

#94 Export command
  src/main/java/jimmy/mcgymmy/logic/commands/ExportCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/test/java/jimmy/mcgymmy/logic/commands/ExportCommandTest.java
Labels: type.Enhancement

#87 Add Import Command
  src/main/java/jimmy/mcgymmy/logic/commands/ExportCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ImportCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/test/java/jimmy/mcgymmy/logic/commands/ImportCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/ParserUtilTest.java
Labels: type.Enhancement

#96 Update UI Class Diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation

#93 Update User Guide
  docs/UserGuide.md
  docs/images/CommandImagesForUG/Add.png
  docs/images/CommandImagesForUG/Clear.png
  docs/images/CommandImagesForUG/DateSelector.png
  docs/images/CommandImagesForUG/Delete.png
  docs/images/CommandImagesForUG/Edit.png
  docs/images/CommandImagesForUG/Export.png
  docs/images/CommandImagesForUG/ExportGUI.png
  docs/images/CommandImagesForUG/Find.png
  docs/images/CommandImagesForUG/Help.png
  docs/images/CommandImagesForUG/Import.png
  docs/images/CommandImagesForUG/ImportGUI.png
  docs/images/CommandImagesForUG/List.png
  docs/images/CommandImagesForUG/Macro.png
  docs/images/CommandImagesForUG/MacroUsage.png
  docs/images/CommandImagesForUG/Tag.png
  docs/images/CommandImagesForUG/Untag.png
  docs/images/Ui.png
Labels: documentation

#100 Update storage class diagram in DG
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation

#97 Add undo command
  src/main/java/jimmy/mcgymmy/logic/commands/EditCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/TagCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/UnTagCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/UndoCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/main/java/jimmy/mcgymmy/model/Model.java
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/main/java/jimmy/mcgymmy/model/food/Food.java
  src/main/java/jimmy/mcgymmy/storage/JsonSerializableMcGymmy.java
  src/test/java/jimmy/mcgymmy/logic/commands/AddCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/EditCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/UndoCommandTest.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
  src/test/java/jimmy/mcgymmy/model/food/FoodTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonSerializableMcGymmyTest.java
Labels: type.Enhancement

#102 Update undo feature in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddToHistoryActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/UndoState0.puml
  docs/diagrams/UndoState1a.puml
  docs/diagrams/UndoState1b.puml
  docs/diagrams/UndoState2a.puml
  docs/diagrams/UndoState2b.puml
  docs/diagrams/UndoState3.puml
  docs/images/AddToHistoryActivityDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/UndoState0.png
  docs/images/UndoState1a.png
  docs/images/UndoState1b.png
  docs/images/UndoState2a.png
  docs/images/UndoState2b.png
  docs/images/UndoState3.png
Labels: documentation

#103 Update Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/ImportSequenceDiagram.puml
  docs/diagrams/TagSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UntagSequenceDiagram.puml
  docs/images/ExportSequenceDiagram.png
  docs/images/ImportSequenceDiagram.png
  docs/images/TagSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UntagSequenceDiagram.png
Labels: documentation

#106 Add find command to Developer Guide
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: documentation

#101 Update logic writeup
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MacroClassDiagram.puml
  docs/diagrams/MacroSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/MacroClassDiagram.png
  docs/images/MacroSequenceDiagram.png
Labels: documentation

#98 Add Macro storage
  src/main/java/jimmy/mcgymmy/MainApp.java
  src/main/java/jimmy/mcgymmy/logic/LogicManager.java
  src/main/java/jimmy/mcgymmy/logic/macro/Macro.java
  src/main/java/jimmy/mcgymmy/logic/macro/MacroList.java
  src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/main/java/jimmy/mcgymmy/model/ReadOnlyUserPrefs.java
  src/main/java/jimmy/mcgymmy/model/UserPrefs.java
  src/main/java/jimmy/mcgymmy/storage/JsonAdaptedMacro.java
  src/main/java/jimmy/mcgymmy/storage/JsonMacroListStorage.java
  src/main/java/jimmy/mcgymmy/storage/JsonSerializableMacroList.java
  src/main/java/jimmy/mcgymmy/storage/MacroListStorage.java
  src/main/java/jimmy/mcgymmy/storage/Storage.java
  src/main/java/jimmy/mcgymmy/storage/StorageManager.java
  src/test/data/JsonMacroListStorageTest/invalidMacroList.json
  src/test/data/JsonMacroListStorageTest/validMacroList.json
  src/test/java/jimmy/mcgymmy/logic/LogicManagerTest.java
  src/test/java/jimmy/mcgymmy/logic/macro/MacroListTest.java
  src/test/java/jimmy/mcgymmy/logic/macro/NewMacroCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonAdaptedMacroTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonMacroListStorageTest.java
  src/test/java/jimmy/mcgymmy/storage/StorageManagerTest.java
Labels: priority.Medium, type.Enhancement

#109 Enable assertion in build.gradle
  build.gradle
Labels: priority.High

#111 Fix formatting stuff in UG
  docs/UserGuide.md
Labels: documentation

#108 Make UndoSequenceDiagram less complicated
  docs/DeveloperGuide.md
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/UndoSequenceDiagram.png
Labels: documentation

#104 Clear Command Modification with UG and UML updates
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ClearSequenceDiagram.puml
  docs/images/ClearSequenceDiagram.png
  src/main/java/jimmy/mcgymmy/logic/commands/ClearCommand.java
  src/main/java/jimmy/mcgymmy/model/Model.java
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/main/java/jimmy/mcgymmy/model/food/Fridge.java
  src/test/java/jimmy/mcgymmy/logic/commands/AddCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/ClearCommandTest.java
  src/test/java/jimmy/mcgymmy/testutil/TypicalFoods.java
Labels: documentation, type.Enhancement

#114 Update ModelClassDiagram in DG
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation

#113 Update architecture sequence diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
Labels: documentation

#107 Add loggers in model component
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/main/java/jimmy/mcgymmy/model/food/Food.java
Labels: priority.Low

#117 Initialize FilteredFoodList w/ a predicate when ModelManager is created
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
Labels: type.Bug

#105 Add granularity to find command
  src/main/java/jimmy/mcgymmy/logic/commands/FindCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/main/java/jimmy/mcgymmy/logic/predicate/DatePredicate.java
  src/main/java/jimmy/mcgymmy/logic/predicate/NameContainsKeywordsPredicate.java
  src/test/java/jimmy/mcgymmy/logic/commands/FindCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserCommandsTest.java
Labels: type.Enhancement

#121 Update undo command to undo all commands except help
  src/main/java/jimmy/mcgymmy/logic/commands/AddCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/TagCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/UnTagCommand.java
  src/main/java/jimmy/mcgymmy/model/History.java
  src/main/java/jimmy/mcgymmy/model/Model.java
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/main/java/jimmy/mcgymmy/model/food/Food.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
  src/test/java/jimmy/mcgymmy/model/food/FoodTest.java
Labels: type.Bug, type.Enhancement

#130 Find command test: Add find tag test that result in multiple foods
  src/test/java/jimmy/mcgymmy/logic/commands/FindCommandTest.java
Labels: type.Bug

#110 Put macros into Model
  src/main/java/jimmy/mcgymmy/MainApp.java
  src/main/java/jimmy/mcgymmy/logic/LogicManager.java
  src/main/java/jimmy/mcgymmy/logic/macro/Macro.java
  src/main/java/jimmy/mcgymmy/logic/macro/MacroList.java
  src/main/java/jimmy/mcgymmy/logic/macro/MacroRunner.java
  src/main/java/jimmy/mcgymmy/logic/macro/NewMacroCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java
  src/main/java/jimmy/mcgymmy/model/History.java
  src/main/java/jimmy/mcgymmy/model/Model.java
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/main/java/jimmy/mcgymmy/model/macro/Macro.java
  src/main/java/jimmy/mcgymmy/model/macro/MacroList.java
  src/main/java/jimmy/mcgymmy/model/macro/exceptions/DuplicateMacroException.java
  src/main/java/jimmy/mcgymmy/storage/JsonAdaptedMacro.java
  src/main/java/jimmy/mcgymmy/storage/JsonMacroListStorage.java
  src/main/java/jimmy/mcgymmy/storage/JsonSerializableMacroList.java
  src/main/java/jimmy/mcgymmy/storage/MacroListStorage.java
  src/main/java/jimmy/mcgymmy/storage/StorageManager.java
  src/test/java/jimmy/mcgymmy/logic/commands/AddCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/macro/MacroRunnerTest.java
  src/test/java/jimmy/mcgymmy/logic/macro/NewMacroCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/McGymmyParserTest.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
  src/test/java/jimmy/mcgymmy/model/macro/MacroListTest.java
  src/test/java/jimmy/mcgymmy/model/macro/MacroTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonAdaptedMacroTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonMacroListStorageTest.java
  src/test/java/jimmy/mcgymmy/testutil/TypicalMacros.java
Labels: type.Enhancement

#80 GUI Updates
  README.md
  build.gradle
  src/main/java/jimmy/mcgymmy/logic/commands/CommandResult.java
  src/main/java/jimmy/mcgymmy/logic/commands/ExitCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ImportCommand.java
  src/main/java/jimmy/mcgymmy/logic/macro/MacroRunner.java
  src/main/java/jimmy/mcgymmy/ui/CommandBox.java
  src/main/java/jimmy/mcgymmy/ui/FoodListPanel.java
  src/main/java/jimmy/mcgymmy/ui/HelpWindow.java
  src/main/java/jimmy/mcgymmy/ui/MainWindow.java
  src/main/java/jimmy/mcgymmy/ui/SummaryDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SummaryDisplay.fxml
  src/test/java/jimmy/mcgymmy/logic/commands/CommandResultTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/ExitCommandTest.java
  src/test/java/jimmy/mcgymmy/model/food/MacronutrientTest.java
Labels: priority.Low, type.Enhancement

#135 Add DatePredicate Tests, update UG with new find command and minor formatting fixes
  docs/UserGuide.md
  src/main/java/jimmy/mcgymmy/logic/predicate/DatePredicate.java
  src/test/java/jimmy/mcgymmy/logic/predicate/DatePredicateTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/NameContainsKeywordsPredicateTest.java
Labels: documentation, type.Enhancement

#131 Update the documents to be up-to-date with new undo command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/UndoState0.puml
  docs/diagrams/UndoState1a.puml
  docs/diagrams/UndoState1b.puml
  docs/diagrams/UndoState2a.puml
  docs/diagrams/UndoState2b.puml
  docs/diagrams/UndoState3.puml
  docs/images/UndoSequenceDiagram.png
  docs/images/UndoState0.png
  docs/images/UndoState1a.png
  docs/images/UndoState1b.png
  docs/images/UndoState2a.png
  docs/images/UndoState2b.png
  docs/images/UndoState3.png
  src/main/java/jimmy/mcgymmy/logic/commands/UndoCommand.java
Labels: documentation

#137 Update UG
  docs/UserGuide.md
Labels: documentation

#142 Minor change to UG for 1.3
  docs/UserGuide.md
Labels: documentation

#119 Bug Fixes
  src/main/java/jimmy/mcgymmy/commons/core/Version.java
  src/main/java/jimmy/mcgymmy/commons/core/index/Index.java
  src/main/java/jimmy/mcgymmy/commons/util/JsonUtil.java
  src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/main/java/jimmy/mcgymmy/logic/parser/parameter/OptionalParameter.java
  src/main/java/jimmy/mcgymmy/model/McGymmy.java
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/main/java/jimmy/mcgymmy/model/food/Fridge.java
  src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java
  src/main/java/jimmy/mcgymmy/storage/JsonMacroListStorage.java
  src/main/java/jimmy/mcgymmy/storage/JsonMcGymmyStorage.java
  src/main/java/jimmy/mcgymmy/storage/JsonUserPrefsStorage.java
  src/main/java/jimmy/mcgymmy/storage/StorageManager.java
  src/main/java/jimmy/mcgymmy/ui/FoodListPanel.java
  src/main/java/jimmy/mcgymmy/ui/MainWindow.java
  src/main/java/jimmy/mcgymmy/ui/SummaryDisplay.java
  src/main/java/jimmy/mcgymmy/ui/UiManager.java
  src/test/data/JsonMcGymmyStorageTest/invalidAndValidFoodMcGymmy.json
  src/test/data/JsonMcGymmyStorageTest/invalidFoodMcGymmy.json
  src/test/data/JsonSerializableMcGymmyTest/duplicateFoodMcGymmy.json
  src/test/data/JsonSerializableMcGymmyTest/invalidFoodMcGymmy.json
  src/test/data/JsonSerializableMcGymmyTest/typicalFoodMcGymmy.json
  src/test/java/jimmy/mcgymmy/AppParametersTest.java
  src/test/java/jimmy/mcgymmy/logic/LogicManagerTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/AddCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/DeleteCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/EditCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/ExitCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/FindCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/TagCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/UnTagCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/macro/MacroRunnerTest.java
  src/test/java/jimmy/mcgymmy/logic/macro/NewMacroCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/ParserUtilTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserCommandsTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/parameter/ParameterSetTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
  src/test/java/jimmy/mcgymmy/model/food/CarbohydrateTest.java
  src/test/java/jimmy/mcgymmy/model/food/FatTest.java
  src/test/java/jimmy/mcgymmy/model/food/ProteinTest.java
  src/test/java/jimmy/mcgymmy/testutil/FoodBuilder.java
  src/test/java/jimmy/mcgymmy/testutil/McGymmyBuilder.java
  src/test/java/jimmy/mcgymmy/testutil/TypicalFoods.java
Labels: priority.Medium, severity.Medium, type.Bug

#133 Add Macro CRUD commands
  src/main/java/jimmy/mcgymmy/logic/commands/ListMacroCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/RemoveMacroCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/main/java/jimmy/mcgymmy/logic/parser/parameter/AbstractParameter.java
  src/main/java/jimmy/mcgymmy/logic/parser/parameter/OptionalParameter.java
  src/main/java/jimmy/mcgymmy/model/macro/MacroList.java
  src/test/java/jimmy/mcgymmy/logic/commands/ListMacroCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/RemoveMacroCommandTest.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
Labels: type.Enhancement

#149 Update images for UG with new GUI
  docs/UserGuide.md
  docs/images/CommandImagesForUG/Add.png
  docs/images/CommandImagesForUG/Delete.png
  docs/images/CommandImagesForUG/Deletemacro.png
  docs/images/CommandImagesForUG/Edit.png
  docs/images/CommandImagesForUG/Export.png
  docs/images/CommandImagesForUG/Find.png
  docs/images/CommandImagesForUG/Help.png
  docs/images/CommandImagesForUG/Import.png
  docs/images/CommandImagesForUG/List.png
  docs/images/CommandImagesForUG/Listmacro.png
  docs/images/CommandImagesForUG/Macro.png
  docs/images/CommandImagesForUG/Tag.png
  docs/images/CommandImagesForUG/Undo.png
  docs/images/CommandImagesForUG/Untag.png
  docs/images/Ui.png
Labels: documentation

#143 Clear command and you language
  docs/UserGuide.md
Labels: documentation

#147 Bug Fix
  src/main/java/jimmy/mcgymmy/MainApp.java
  src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java
  src/main/java/jimmy/mcgymmy/ui/FoodListPanel.java
  src/main/java/jimmy/mcgymmy/ui/MainWindow.java
  src/main/java/jimmy/mcgymmy/ui/SummaryDisplay.java
Labels: type.Bug

#151 Update UG
  docs/UserGuide.md
  docs/images/CommandImagesForUG/Clear.png
  docs/images/CommandImagesForUG/DateSelector.png
  docs/images/CommandImagesForUG/ExportGUI.png
  docs/images/CommandImagesForUG/FileMenu.png
  docs/images/CommandImagesForUG/ImportGUI.png
  docs/images/CommandImagesForUG/Usage.png
Labels: documentation

#150 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/AddToHistoryActivityDiagram.puml
  docs/images/AddToHistoryActivityDiagram.png
Labels: documentation

#194 Mention that tag name is case-sensitive in UG's tag & untag section
  docs/UserGuide.md
Labels: documentation

#193 Fix error in UG's command summary
  docs/UserGuide.md
Labels: documentation

#192 Add a line break before "For"
  docs/UserGuide.md
Labels: documentation

#195 Update add command's format
  docs/UserGuide.md
Labels: documentation

#198 Add cmd + f for Mac Users in UG
  docs/UserGuide.md
Labels: documentation

#200 UG: change "apart" to "a part"
  docs/UserGuide.md
Labels: documentation

#196 Food#toString: caplitalize protein, carbs and fat
  src/main/java/jimmy/mcgymmy/model/food/Food.java
  src/test/java/jimmy/mcgymmy/model/food/FoodTest.java
Labels: documentation

#197 Limit size of Tags to 20 chars
  docs/UserGuide.md
  src/main/java/jimmy/mcgymmy/model/tag/Tag.java
  src/test/java/jimmy/mcgymmy/model/tag/TagTest.java
Labels: type.Bug

#202 Undo class: change success message from "undo" to "undid"
  src/main/java/jimmy/mcgymmy/logic/commands/UndoCommand.java
Labels: documentation

#206 Fix Grammar of tag command
  src/main/java/jimmy/mcgymmy/model/tag/Tag.java
Labels: type.Bug

#205 Update Images
  docs/images/CommandImagesForUG/Add.png
  docs/images/CommandImagesForUG/Clear.png
  docs/images/CommandImagesForUG/DateSelector.png
  docs/images/CommandImagesForUG/Delete.png
  docs/images/CommandImagesForUG/Deletemacro.png
  docs/images/CommandImagesForUG/Edit.png
  docs/images/CommandImagesForUG/Export.png
  docs/images/CommandImagesForUG/ExportGUI.png
  docs/images/CommandImagesForUG/FileMenu.png
  docs/images/CommandImagesForUG/Find.png
  docs/images/CommandImagesForUG/Help.png
  docs/images/CommandImagesForUG/Import.png
  docs/images/CommandImagesForUG/ImportGUI.png
  docs/images/CommandImagesForUG/List.png
  docs/images/CommandImagesForUG/Listmacro.png
  docs/images/CommandImagesForUG/ListmacroCommand.png
  docs/images/CommandImagesForUG/Macro.png
  docs/images/CommandImagesForUG/MacroUsage.png
  docs/images/CommandImagesForUG/Tag.png
  docs/images/CommandImagesForUG/Undo.png
  docs/images/CommandImagesForUG/Untag.png
  docs/images/CommandImagesForUG/Usage.png
  docs/images/Ui.png
Labels: documentation

#204 Add spaces for Commands
  docs/UserGuide.md
Labels: documentation

#201 Update MESSAGE_CONSTRAINTS to non-negative integer values
  docs/UserGuide.md
  src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java
Labels: type.Bug
