Repository AY2021S1-CS2103T-W17-3/tp, pull requests merged in 2020-11, with the labels that each got.

#212 Disable DatePicker
  src/main/java/jimmy/mcgymmy/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: severity.VeryLow, type.Bug

#213 Fix Tag and untag command executing wrongly after finding
  docs/UserGuide.md
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/test/java/jimmy/mcgymmy/logic/commands/UnTagCommandTest.java
Labels: documentation, type.Bug

#203 Change Name of arguments in the MacroNutrient Parameters
  src/main/java/jimmy/mcgymmy/logic/commands/AddCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/EditCommand.java
Labels: type.Bug

#152 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#218 Fix 214
  src/main/java/jimmy/mcgymmy/model/food/Carbohydrate.java
  src/main/java/jimmy/mcgymmy/model/food/Fat.java
  src/main/java/jimmy/mcgymmy/model/food/Protein.java
  src/test/java/jimmy/mcgymmy/logic/parser/ParserUtilTest.java
  src/test/java/jimmy/mcgymmy/model/food/CarbohydrateTest.java
  src/test/java/jimmy/mcgymmy/model/food/FatTest.java
  src/test/java/jimmy/mcgymmy/model/food/ProteinTest.java
Labels: code quality improvements

#223 Change undo behavior
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/jimmy/mcgymmy/model/History.java
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
Labels: severity.Medium, type.Bug

#224 Add duong's PPP
  docs/team/duong.md
Labels: documentation

#217 Fix minor bugs in Macro
  docs/UserGuide.md
  src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandHelpUtil.java
  src/test/java/jimmy/mcgymmy/logic/parser/McGymmyParserTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandHelpUtilTest.java
Labels: documentation, type.Bug

#216 Refactor IllegalArgumentException to IllegalValueException
  src/main/java/jimmy/mcgymmy/MainApp.java
  src/main/java/jimmy/mcgymmy/commons/core/Version.java
  src/main/java/jimmy/mcgymmy/commons/util/AppUtil.java
  src/main/java/jimmy/mcgymmy/commons/util/StringUtil.java
  src/main/java/jimmy/mcgymmy/logic/commands/AddCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/main/java/jimmy/mcgymmy/logic/predicate/NameContainsKeywordsPredicate.java
  src/main/java/jimmy/mcgymmy/logic/predicate/TagContainsKeywordsPredicate.java
  src/main/java/jimmy/mcgymmy/model/date/Date.java
  src/main/java/jimmy/mcgymmy/model/food/Carbohydrate.java
  src/main/java/jimmy/mcgymmy/model/food/Fat.java
  src/main/java/jimmy/mcgymmy/model/food/Food.java
  src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java
  src/main/java/jimmy/mcgymmy/model/food/Name.java
  src/main/java/jimmy/mcgymmy/model/food/Protein.java
  src/main/java/jimmy/mcgymmy/model/tag/Tag.java
  src/main/java/jimmy/mcgymmy/model/util/SampleDataUtil.java
  src/main/java/jimmy/mcgymmy/storage/JsonAdaptedFood.java
  src/test/java/jimmy/mcgymmy/commons/core/VersionTest.java
  src/test/java/jimmy/mcgymmy/commons/util/AppUtilTest.java
  src/test/java/jimmy/mcgymmy/commons/util/StringUtilTest.java
  src/test/java/jimmy/mcgymmy/logic/LogicManagerTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/AddCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/ClearCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/EditCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/FindCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/TagCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/UnTagCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/DatePredicateTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/FoodContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/TagContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/model/McGymmyTest.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
  src/test/java/jimmy/mcgymmy/model/date/DateTest.java
  src/test/java/jimmy/mcgymmy/model/food/CarbohydrateTest.java
  src/test/java/jimmy/mcgymmy/model/food/FatTest.java
  src/test/java/jimmy/mcgymmy/model/food/FoodTest.java
  src/test/java/jimmy/mcgymmy/model/food/FridgeTest.java
  src/test/java/jimmy/mcgymmy/model/food/MacronutrientTest.java
  src/test/java/jimmy/mcgymmy/model/food/NameTest.java
  src/test/java/jimmy/mcgymmy/model/food/ProteinTest.java
  src/test/java/jimmy/mcgymmy/model/tag/TagTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonAdaptedFoodTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonMcGymmyStorageTest.java
  src/test/java/jimmy/mcgymmy/testutil/FoodBuilder.java
  src/test/java/jimmy/mcgymmy/testutil/TypicalFoods.java
Labels: priority.High, type.Bug

#225 Model class: fix typo in javadoc
  src/main/java/jimmy/mcgymmy/model/Model.java
Labels: documentation

#227 Junhua PPP
  docs/AboutUs.md
  docs/team/jh123x.md
Labels: documentation

#231 Rename duong.md to aidoxe-123.md
  docs/team/aidoxe-123.md
Labels: documentation

#229 Add test for find and clear
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
Labels: type.Enhancement

#238 Update Junhua PPP
  docs/team/duong.md
  docs/team/jh123x.md
Labels: documentation

#219 Fix 215
  src/main/java/jimmy/mcgymmy/commons/core/index/Index.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/main/java/jimmy/mcgymmy/model/food/Carbohydrate.java
  src/main/java/jimmy/mcgymmy/model/food/Fat.java
  src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java
  src/main/java/jimmy/mcgymmy/model/food/Protein.java
  src/test/java/jimmy/mcgymmy/logic/parser/ParserUtilTest.java
  src/test/java/jimmy/mcgymmy/model/food/MacronutrientTest.java
Labels: code quality improvements

#232 Several minor code quality improvements + DG update
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/MacroClassDiagram.puml
  docs/diagrams/MacroSequenceDiagram.puml
  docs/images/MacroClassDiagram.png
  docs/images/MacroSequenceDiagram.png
  docs/team/joeychensmart.md
  src/main/java/jimmy/mcgymmy/logic/commands/Command.java
  src/main/java/jimmy/mcgymmy/logic/commands/ListMacroCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/RemoveMacroCommand.java
  src/main/java/jimmy/mcgymmy/logic/macro/MacroRunner.java
  src/main/java/jimmy/mcgymmy/logic/macro/NewMacroCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/main/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParser.java
  src/main/java/jimmy/mcgymmy/logic/parser/exceptions/ParameterConflictException.java
  src/main/java/jimmy/mcgymmy/logic/parser/parameter/AbstractParameter.java
  src/main/java/jimmy/mcgymmy/logic/parser/parameter/OptionalParameter.java
  src/main/java/jimmy/mcgymmy/logic/parser/parameter/Parameter.java
  src/main/java/jimmy/mcgymmy/model/macro/Macro.java
  src/main/java/jimmy/mcgymmy/model/macro/MacroList.java
  src/main/java/jimmy/mcgymmy/model/macro/exceptions/DuplicateMacroException.java
  src/main/java/jimmy/mcgymmy/storage/JsonMacroListStorage.java
  src/main/java/jimmy/mcgymmy/storage/MacroListStorage.java
  src/test/java/jimmy/mcgymmy/logic/commands/CommandTestUtil.java
  src/test/java/jimmy/mcgymmy/logic/commands/DeleteCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/ListMacroCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/McGymmyParserTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserCommandsTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/PrimitiveCommandParserTest.java
Labels: documentation, type.Enhancement

#242 My PPP
  docs/team/dcchan98.md
Labels: documentation

#236 Proposed modifications to UG (You-ify)
  docs/UserGuide.md
Labels: documentation

#243 Junhua PPP
  docs/team/jh123x.md
Labels: documentation

#235 Fix 233 Check JavaDocs
  src/main/java/jimmy/mcgymmy/logic/commands/ClearCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ExportCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ImportCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ListCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/RemoveMacroCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/TagCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/UnTagCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/UndoCommand.java
  src/main/java/jimmy/mcgymmy/model/McGymmy.java
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/main/java/jimmy/mcgymmy/model/ReadOnlyMcGymmy.java
  src/main/java/jimmy/mcgymmy/model/date/Date.java
  src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java
  src/main/java/jimmy/mcgymmy/model/food/Name.java
  src/main/java/jimmy/mcgymmy/model/macro/MacroList.java
  src/main/java/jimmy/mcgymmy/storage/JsonMacroListStorage.java
  src/main/java/jimmy/mcgymmy/storage/JsonUserPrefsStorage.java
  src/main/java/jimmy/mcgymmy/storage/Storage.java
  src/main/java/jimmy/mcgymmy/ui/MainWindow.java
  src/main/java/jimmy/mcgymmy/ui/SummaryDisplay.java
  src/main/java/jimmy/mcgymmy/ui/Ui.java
Labels: code quality improvements

#240 History class: create test cases ...
  src/main/java/jimmy/mcgymmy/model/History.java
  src/test/java/jimmy/mcgymmy/model/HistoryTest.java
Labels: code quality improvements

#241 Add tests to improve coverage
  src/main/java/jimmy/mcgymmy/commons/core/Messages.java
  src/main/java/jimmy/mcgymmy/commons/exceptions/IllegalValueException.java
  src/main/java/jimmy/mcgymmy/logic/commands/FindCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/main/java/jimmy/mcgymmy/logic/parser/exceptions/ParseException.java
  src/main/java/jimmy/mcgymmy/model/food/Food.java
  src/test/java/jimmy/mcgymmy/logic/parser/ParserUtilTest.java
  src/test/java/jimmy/mcgymmy/model/McGymmyTest.java
  src/test/java/jimmy/mcgymmy/model/UserPrefsTest.java
  src/test/java/jimmy/mcgymmy/model/date/DateTest.java
  src/test/java/jimmy/mcgymmy/model/food/NameTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonUserPrefsStorageTest.java
  src/test/java/jimmy/mcgymmy/storage/StorageManagerTest.java
Labels: code quality improvements

#208 Fix wrong message error when integer > max_int
  docs/UserGuide.md
  src/main/java/jimmy/mcgymmy/commons/core/index/Index.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/test/java/jimmy/mcgymmy/logic/parser/ParserUtilTest.java
Labels: severity.Medium, type.Bug

#237 Fix 234
  src/main/java/jimmy/mcgymmy/logic/commands/AddCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/EditCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ExportCommand.java
  src/main/java/jimmy/mcgymmy/logic/commands/ImportCommand.java
  src/main/java/jimmy/mcgymmy/model/ModelManager.java
  src/main/java/jimmy/mcgymmy/model/date/Date.java
  src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java
  src/main/java/jimmy/mcgymmy/storage/JsonAdaptedFood.java
  src/test/java/jimmy/mcgymmy/model/food/MacronutrientTest.java
Labels: code quality improvements, type.Bug

#230 Add more Test cases for Commons and Logic
  src/main/java/jimmy/mcgymmy/logic/commands/ExportCommand.java
  src/main/java/jimmy/mcgymmy/logic/parser/ParserUtil.java
  src/test/data/ExportData/Test.json
  src/test/java/jimmy/mcgymmy/commons/core/ConfigTest.java
  src/test/java/jimmy/mcgymmy/commons/core/GuiSettingsTest.java
  src/test/java/jimmy/mcgymmy/commons/core/index/IndexTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/CommandResultTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/DeleteCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/ExportCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/ImportCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/macro/NewMacroCommandTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/ParserUtilTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/parameter/OptionalParameterTest.java
  src/test/java/jimmy/mcgymmy/logic/parser/parameter/ParameterTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/DatePredicateTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/FoodContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/logic/predicate/TagContainsKeywordsPredicateTest.java
  src/test/java/jimmy/mcgymmy/model/McGymmyTest.java
Labels: code quality improvements, type.Enhancement

#246 Fix 245
  src/main/java/jimmy/mcgymmy/model/date/Date.java
  src/test/java/jimmy/mcgymmy/logic/commands/ImportCommandTest.java
  src/test/java/jimmy/mcgymmy/model/date/DateTest.java
Labels: code quality improvements, type.Bug

#247 Add PPP for chewypiano
  docs/team/chewypiano.md
Labels: documentation

#249 Junhua's PPP
  docs/team/jh123x.md
Labels: documentation

#260 Delete unused ppp files
  docs/team/duong.md
  docs/team/johndoe.md
Labels: documentation

#256 Add Labels to UI pictures
  docs/images/CommandImagesForUG/Add.png
  docs/images/CommandImagesForUG/Clear.png
  docs/images/CommandImagesForUG/DateSelector.png
  docs/images/CommandImagesForUG/Delete.png
  docs/images/CommandImagesForUG/Deletemacro.png
  docs/images/CommandImagesForUG/Edit.png
  docs/images/CommandImagesForUG/Export.png
  docs/images/CommandImagesForUG/ExportGUI.png
  docs/images/CommandImagesForUG/Find.png
  docs/images/CommandImagesForUG/Help.png
  docs/images/CommandImagesForUG/Import.png
  docs/images/CommandImagesForUG/ImportGUI.png
  docs/images/CommandImagesForUG/List.png
  docs/images/CommandImagesForUG/Listmacro.png
  docs/images/CommandImagesForUG/ListmacroCommand.png
  docs/images/CommandImagesForUG/Macro.png
  docs/images/CommandImagesForUG/Tag.png
  docs/images/CommandImagesForUG/Undo.png
  docs/images/CommandImagesForUG/Untag.png
Labels: documentation

#261 DG: Update the implementation of undo
  docs/DeveloperGuide.md
Labels: documentation

#244 UG-DG Update
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
Labels: documentation

#264 Add invalid date format to MESSAGE_CONSTRAINTS
  src/main/java/jimmy/mcgymmy/model/date/Date.java
Labels: severity.Low, type.Bug

#267 Add info to help command
  docs/UserGuide.md
Labels: documentation

#266 Update AboutUs.md
  docs/AboutUs.md
Labels: documentation

#258 Add section which shows optional arguments for list macro
  docs/UserGuide.md
  src/main/resources/view/DarkTheme.css
Labels: documentation

#271 UG update
  docs/UserGuide.md
Labels: documentation

#272 UG's 5.8: add note that user must use tag/untag cmd for editing tag
  docs/UserGuide.md
Labels: documentation

#275 Add Non-Functional Requirements.
  docs/DeveloperGuide.md
Labels: documentation

#276 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#277 Fix macro UG bugs
  docs/UserGuide.md
  docs/images/CommandImagesForUG/Macro.png
Labels: documentation

#278 Junhua PPP Update
  docs/team/jh123x.md
Labels: documentation

#279 Duong's PPP: fix formatting errors
  docs/team/aidoxe-123.md
Labels: documentation

#280 Fix typos in code and comments
  src/main/java/jimmy/mcgymmy/logic/commands/FindCommand.java
  src/test/java/jimmy/mcgymmy/logic/LogicManagerTest.java
  src/test/java/jimmy/mcgymmy/logic/commands/FindCommandTest.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
  src/test/java/jimmy/mcgymmy/storage/JsonAdaptedFoodTest.java
Labels: code quality improvements

#273 DG: add use case for undo
  docs/DeveloperGuide.md
Labels: documentation

#282 Fix links for peer programming
  docs/team/chewypiano.md
  docs/team/dcchan98.md
  docs/team/jh123x.md
Labels: documentation

#248 Model test
  src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java
  src/test/java/jimmy/mcgymmy/model/ModelManagerTest.java
  src/test/java/jimmy/mcgymmy/model/UserPrefsTest.java
  src/test/java/jimmy/mcgymmy/model/food/CarbohydrateTest.java
  src/test/java/jimmy/mcgymmy/model/food/FatTest.java
  src/test/java/jimmy/mcgymmy/model/food/FoodTest.java
  src/test/java/jimmy/mcgymmy/model/food/MacronutrientTest.java
  src/test/java/jimmy/mcgymmy/model/food/NameTest.java
  src/test/java/jimmy/mcgymmy/model/food/ProteinTest.java
  src/test/java/jimmy/mcgymmy/model/macro/MacroListTest.java
  src/test/java/jimmy/mcgymmy/model/macro/MacroTest.java
  src/test/java/jimmy/mcgymmy/model/tag/TagTest.java
Labels: code quality improvements

#284 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#268 Add User Story
  docs/DeveloperGuide.md
Labels: documentation

#298 DG: Update undo state diagram
  docs/DeveloperGuide.md
  docs/diagrams/UndoState0.puml
  docs/diagrams/UndoState1a.puml
  docs/diagrams/UndoState1b.puml
  docs/diagrams/UndoState2a.puml
  docs/diagrams/UndoState2b.puml
  docs/diagrams/UndoState3.puml
  docs/images/UndoState0.png
  docs/images/UndoState1a.png
  docs/images/UndoState1b.png
  docs/images/UndoState2a.png
  docs/images/UndoState2b.png
  docs/images/UndoState3.png
Labels: documentation

#299 Update Junhua PPP
  docs/team/jh123x.md
Labels: documentation

#274 Update Use cases
  docs/DeveloperGuide.md
Labels: documentation

#300 Update Github links in PPP
  docs/team/jh123x.md
Labels: documentation

#301 Update Junhua PPP
  docs/team/jh123x.md
Labels: documentation

#302 Minor changes to PPP formatting
  docs/team/joeychensmart.md
Labels: documentation

#297 Fix ugdg bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/MacroSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/MacroSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/jimmy/mcgymmy/model/Model.java
Labels: documentation

#305 Fix undo UML diagrams
  docs/diagrams/UndoState2a.puml
  docs/diagrams/UndoState2b.puml
  docs/diagrams/UndoState3.puml
  docs/images/UndoState2a.png
  docs/images/UndoState2b.png
  docs/images/UndoState3.png
Labels: documentation

#308 Dg last change
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#310 Add credits for CS2101
  docs/UserGuide.md
Labels: documentation
